### ISSUE TITLE
cc2538 low signal

### ISSUE THREAD

**Issue by 1igeza** [jethome-ru/zigbee-firmware#1]
I've got:
https://www.aliexpress.com/item/4000848221784.html?spm=a2g0s.9042311.0.0.438e4c4dOodsHr
I tried it with external antenna and with internal after switching resistor, but in both cases I have low signal. Any idea how can it be fixed? I'm using it  as a router. The coordinator is cc1352 without amplifier and Lqi from 4m distance without any objects between is  6 (cc2538 with external antenna). I have another router cc2530 with external antenna next to cc2538 and it has better lqi: 22 with the same distance from coordinator. 
![Bez tytułu](https://user-images.githubusercontent.com/39980292/93608303-beeaf280-f9ca-11ea-89f6-e40ae8194017.png)
![IMG_20200918_162237](https://user-images.githubusercontent.com/39980292/93608772-50f2fb00-f9cb-11ea-8bbd-7c79633a9031.jpg)

**Comment by 0x3EC** [comment]
Hi, 1igeza!

It is not a good idea to place the power wires and interface close to the RF area. Fix it.

Have you tried changing the antenna to cc2538?

**Comment by 1igeza** [comment]
Thank you for reply, 
I'm testing cc2538 with internal antenna. I can compare it to cc1352(tx power about 4,5 dBm) without amplifier. Distance between cc2538(router) and cc1352(coordinator) is about 50cm. Antenna in both devices is pointing in this same direction. So if the RX Sensitivity in both devices is about -103 dBm, that's mean the signal should be at similar level using internal antenna? 
![3](https://user-images.githubusercontent.com/39980292/95500015-76f63480-09a6-11eb-8e5e-bf59bd4a42a9.png)
![1](https://user-images.githubusercontent.com/39980292/95500017-778ecb00-09a6-11eb-9dc3-7e91e336ddc3.jpg)

I have one more question, The firmware I'm using is jh_2538_router_20200522.hex, in zigbee2mqtt I don't see LQI and I'm getting "Failed to execute routing table for 'Router cc2538'", I sniff the traffic and probably this firmware doesn't support it, Is that correct or I am doing something wrong?

```
ZigBee Device Profile, Routing Table Response, Status: Not Supported
    Sequence Number: 65
    Status: Not Supported (132)
    Table Size: 0
    Index: 0
    Table Count: 0

```

**Comment by 0x3EC** [comment]
Yes, the values should be similar.

_I have one more question, The firmware I'm using is jh_2538_router_20200522.hex, in zigbee2mqtt I don't see LQI and I'm getting "Failed to execute routing table for 'Router cc2538'", I sniff the traffic and probably this firmware doesn't support it, Is that correct or I am doing something wrong?_
This is due to the fact that z2m does not support this device. We will try to solve it.

A good question about the routing table. I'll figure out what's the matter.

Thanks!

**Comment by 1igeza** [comment]
Today I updated coordinator to CC1352P_2_20201026.hex, upgraded zigbee2mgtt and pair again Router cc2538. I don't know what helped but now routing table works as it should.
![1](https://user-images.githubusercontent.com/39980292/97215153-632f3880-17c4-11eb-8958-3b55008d0be9.png)

**Comment by Hacker-CB** [comment]
`CC1352P_2_20201026.hex` is not our firmware. Our firmwares are [here](https://github.com/jethome-ru/zigbee-firmware/tree/master/ti/coordinator/cc2538_cc2592). All have prefix `JH_2538_2592_`

**Comment by 1igeza** [comment]
I know, I'm using you firmware (jh_2538_router_20200522.hex) in router cc2538 and with routing table from cc2538 I had a problem.
