### ISSUE TITLE
Add please Link Quality to 2538 router

### ISSUE THREAD

**Issue by 2scorpio** [jethome-ru/zigbee-firmware#10]
Hello.
Add please "Link Quality" parametr to 2358 router firmware.

**Comment by yiirus** [comment]
I also vote for that. This is sorely lacking.

**Comment by hrosak88** [comment]
Link quality will be nice. Thank you.

**Comment by Ne0k** [comment]
Yes, I will like it too!

**Comment by sergey81-81** [comment]
Действительно качество связи очень низкое.

**Comment by 0x3EC** [comment]
In version jh_2538_router_20210115 this is added.
