### ISSUE TITLE
jh_2538_router_20200522 не отправляет LQI

### ISSUE THREAD

**Issue by Anonym-tsk** [jethome-ru/zigbee-firmware#14]
Стик Modkam
Прошивка jh_2538_router_20200522.zip
LQI или не отправляет вообще, или отправляет один раз при включении
Last Seen также не обновляется
При этом, сам роутер работает, устройства подключаются

<img width="333" alt="Zigbee2MQTT 2021-03-01 11-16-24" src="https://user-images.githubusercontent.com/1973755/109469870-b02b6000-7a7f-11eb-8d3d-d29e210b2c69.png">
<img width="563" alt="Zigbee2MQTT 2021-03-01 11-16-05" src="https://user-images.githubusercontent.com/1973755/109469881-b1f52380-7a7f-11eb-9a39-53624ca7f166.png">

**Comment by Anonym-tsk** [comment]
Конвертер в readme неправильный. Вот корректный с репортом температуры и lqi
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const e = exposes.presets;

const device = {
    zigbeeModel: ['cc2538.router.v2'],
    model: 'cc2538.router.v2',
    vendor: 'jethome',
    description: 'zigbee router cc2538 with temperature sensor',
    fromZigbee: [fz.ignore_basic_report, fz.device_temperature],
    toZigbee: [],
    exposes: [e.device_temperature(), e.linkquality()],
};

module.exports = device;
```

@0x3EC можно ли изменить частоту отправки данных с одной секунды? Кажется, это очень часто - брокера заваливает сообщениями. Секунд 15 было бы оптимально

**Comment by 0x3EC** [comment]
@Anonym-tsk 
Спасибо за конвертер.
Проверьте версию jh_2538_router_20210310. Период отправки изменен на 15 сек.

**Comment by Anonym-tsk** [comment]
@0x3EC 
Всё работает, спасибо.
Сделал PR с конвертером в z2m
https://github.com/Koenkk/zigbee-herdsman-converters/pull/2345
