### ISSUE TITLE
Устройства LIDL как рутеры

### ISSUE THREAD

**Issue by balonchiks** [jethome-ru/zigbee-firmware#17]
Добрый день, пользуюсь прошивкой от 20201010 на modkam стике v3, и заметил очень странное поведение сети. В сети имеется большое количество устройств из Лидла, в частности [3 лед ленты](https://www.zigbee2mqtt.io/devices/HG06104A.html), порядка [7 лампочек](https://www.zigbee2mqtt.io/devices/HG06106C.html) (синие на карте внизу), однако устройства прдпочитают соединятся напрямую с координатором (зоопарк устройств внизу картинки) даже не смотря на то, что большинство из них физически в нескольких сантиметрах от синих рутеров лидл, они все равно соединяются с координатором на прямую, который в 8-10 метрах от них. Те несколько синих устройства (рутеры) около который есть желтые enddevices - это рутеры sonoff basiczbr3.

![изображение](https://user-images.githubusercontent.com/31212478/117121754-56078d80-ad95-11eb-853d-aa7348cf9594.png)

Не подскажите, такое поведение сети - это нормально? Спасибо!

**Comment by Hacker-CB** [comment]
Добрый день.

1.Карта не всегда соответствует действительности.
2. Да, это нормально.

На будущее, с такими вопросами лучше в https://t.me/zigbeer
