### ISSUE TITLE
Pin assignment

### ISSUE THREAD

**Issue by Ellissar** [jethome-ru/zigbee-firmware#18]
I can't find the exact information.
Can you please tell me whether I have identified the pins that are used in the JH_2538_2592_ZNP_UART_20201010.hex firmware correctly or not?
RX = PA0
TX = PA1
CTS = I could not find this information.
RTS = PD1

I suggest you add information about the assignment of contacts and connection parameters (speed, parity, etc.) to the "README.md" file.
![Буфер обмена01](https://user-images.githubusercontent.com/8780018/125802809-8e226cd1-e65a-492f-add0-34b1f4f4e889.png)
![Буфер обмена01](https://user-images.githubusercontent.com/8780018/125803393-e5ca0689-c9de-432d-8610-86d61812bd96.png)

**Comment by 0x3EC** [comment]
Hi, @Ellissar 

115200 8n1, No flow control
PA0 - RX
PA1 - TX
PB0 - CTS (no used)
PD1 - RTS (no used)

Updated readme.

**Comment by Ellissar** [comment]
Hi, @0x3EC
Thank you for your prompt reply.
