### ISSUE TITLE
Checking the performance of the CC2538 using the usb <-> ttl converter.

### ISSUE THREAD

**Issue by Ellissar** [jethome-ru/zigbee-firmware#19]
I am using JH_2538_2592_ZNP_UART_20201010.hex
I suspect my CC2538 is defective.
How to check the operability of a microcircuit using a USB <-> TTL adapter?
What commands can be sent through the terminal to receive a response from the CC2538?

**Comment by 0x3EC** [comment]
Hi, @Ellissar 

After a hard reset CC2538 sends a packet to the port:
FE 06 41 80 xx xx xx xx xx xx xx 
(the first 4 bytes are exactly as I indicated)
You can set up communication through the terminal, restart 2538 and see the result.

Maybe your 2538 goes into the bootloader after a reset? PA7 must be high to run the firmware.

**Comment by Ellissar** [comment]
Hi, @0x3EC 
I have connected the following pins to CC2538:
3.3V
GND
PA0
PA1
PA7 is connected directly to 3.3V. All the time.

The answer comes (FE 06 41 80 00 02 02 02 07 02 C0), but not always.
I will understand further, I assume that there is not enough power to turn it on.

Thanks!
