### ISSUE TITLE
20220219 firmware for cc2652

### ISSUE THREAD

**Issue by Anonym-tsk** [jethome-ru/zigbee-firmware#23]
Please build firmware based on [20220219](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) version for cc2652 stick.

**Comment by hacker-cb** [comment]
@0x3EC could you build please?

CC: @a-kazantsev

**Comment by 0x3EC** [comment]
> @0x3EC could you build please?
> 
> CC: @a-kazantsev

Ok

**Comment by 0x3EC** [comment]
> Please build firmware based on [20220219](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin) version for cc2652 stick.

[CC1352P2_CC2652P_launchpad_coordinator_20220524](https://github.com/jethome-ru/zigbee-firmware/tree/master/ti/coordinator/cc2652)
