### ISSUE TITLE
Problems with migration from CC2531 (stack 1.2) to CC2528 (stack 3.0)

### ISSUE THREAD

**Issue by mozdyn** [jethome-ru/zigbee-firmware#5]
Hi there!
I'm trying to replace CC2531 (stack 1.2) to CC2528 (stack 3.0), unfortunately without success.
My setup is Homeassistant 0.118.5, Hass.io 5.8, Zigbee2MQTT version 1.16.2, CC2538 with latest jethome-ru/zigbee-firmware/cc2538_cc2592/MODKAMRU_V3
Flashed device according https://www.zigbee2mqtt.io/information/flashing_the_cc2538.html
Reconfigured zigbee2mqtt:
I've set rtscts: false
Increased pan_id
Updated serial port and checked permissions for new serial port with:
test -w [PORT] && echo success || echo failure
Deleted database.db
Have network key in place.

But Zigbee2mqtt do not want to start:

```
Zigbee2MQTT:info  2021-01-02 18:44:11: Starting Zigbee2MQTT version 1.16.2 (commit #1.16.2)
Zigbee2MQTT:info  2021-01-02 18:44:11: Starting zigbee-herdsman (0.13.37)
Zigbee2MQTT:debug 2021-01-02 18:44:11: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[14],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6756},"serialPort":{"path":"/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00","rtscts":false}}'
Zigbee2MQTT:error 2021-01-02 18:44:14: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-01-02 18:44:14: Failed to start zigbee
Zigbee2MQTT:error 2021-01-02 18:44:14: Exiting...
Zigbee2MQTT:error 2021-01-02 18:44:14: Error: SREQ '--> SYS - osalNvWrite - {"id":3,"len":1,"offset":0,"value":{"type":"Buffer","data":[2]}}' failed with status '(0x0a: NV_OPER_FAILED)' (expected '(0x00: SUCCESS)')
    at Znp.<anonymous> (/zigbee2mqtt-1.16.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.16.2/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)

```
Any idea what to check? Or idea what the error means? 
@Koenkk from zigbee2mqtt suggested to raise an issue question here.

**Comment by Hacker-CB** [comment]
Hi!
Try to flasjh firmware, and after delete all nvram with the next script: https://github.com/Koenkk/zigbee2mqtt/blob/dev/scripts/zStackEraseAllNvMem.js

**Comment by mozdyn** [comment]
Thanks! 
Any manual how to use the script?

**Comment by Hacker-CB** [comment]
Try to run it. It has embeded help.

**Comment by earion** [comment]
For me such solution didn't works I run script which shows all NVRam cells erased byt still see:
`
Zigbee2MQTT:info  2021-02-09 17:42:51: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-02-09.17-42-50' filename: log.txt
Zigbee2MQTT:info  2021-02-09 17:42:52: Starting Zigbee2MQTT version 1.17.1 (commit #99274c7)
Zigbee2MQTT:info  2021-02-09 17:42:52: Starting zigbee-herdsman (0.13.59)
Zigbee2MQTT:error 2021-02-09 17:42:56: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-02-09 17:42:56: Failed to start zigbee
Zigbee2MQTT:error 2021-02-09 17:42:56: Exiting...
Zigbee2MQTT:error 2021-02-09 17:42:56: Error: SREQ '--> SYS - osalNvWrite - {"id":135,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}}' failed with status '(0x0a: NV_OPER_FAILED)' (expected '(0x00: SUCCESS)')
    at Znp.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
`

**Comment by Hacker-CB** [comment]
Seems that something is wrong with your stick.
Try 
* flash latest firmware (be sure that you are using correct version, depending on which port has your stick (USB or UART)
* run `node scripts/zStackEraseAllNvMem.js /dev/XXXX` from the z2m folder, where `XXXX` is your device

**Comment by handfreezer** [comment]
Hello, I feel to be in the same situation, But I open an issue into Z2M & CC2538 adventure ([link here](https://github.com/Koenkk/zigbee2mqtt/discussions/1568#discussioncomment-567788)), here is a copy/paste:


**My config** : debian Buster 10 + Z2M git:master (all updated 2 days ago, I had to npm install deep-diff). Z2M is running under an unprivilege user, but the user is in group dialup which give him access to /dev/ttyACM0 (it is working well with a CC2531).
To make the migration, I stopped Z2M, then removed "data" dir content, and put back a copy of configuration.yaml (devices list removed).

**Process of test:** I'm connecting it through direct USB without RS232<>USB converter. I mentionned uSB and UART speaking about JH firmware, because I'm a little bit lost about the differences between each. I will work now only with JH_2538_2592_ZNP_USB_20201010.hex except if someone explian to use the other one.

**Here is the configuration file before starting:**
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyACM0
  adapter: zstack
advanced:
  timestamp_format: YYYYMMDD-HHmmss
  loglevel: debug
  log_directory: data/log
  log_file: Z2M_CC2538_%TIMESTAMP%.log
  log_rotation: true
  baudrate: 115200
  rtscts: false
frontend:
  port: 8123
  host: 0.0.0.0
  auth_token: TheAuthToken
#blocklist:
#passlist:

**Check list of "why Z2M do not start" link:**
*change port with /dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00
*write access to ttyACM0 : ok (checked with test -w commande)
*adding pan_id: 0x1a63
*set log level to debug in configuration.yaml and set env variable export < DEBUG="zigbee-herdsman*" >
*no problem for opening port
*not under RPi
*checking dmesg -w : no alert
*not under openhab
*not a CC2540, but a CC2538 ;-)
*hciuart : module loaded, not used (counter=0), systemctl status hciuart => no service found
*reset button used event if not under CC2538
*CC26xr1 coordinator only : not concerned
*not yet concerned by limit of devices number of CC2531
*only one interface if00, no doubt on choice


**Debug level here:**

> zigbee2mqtt_cc2538/git$ ./launch_debug.sh
> + export 'DEBUG=zigbee-herdsman*'
> + DEBUG='zigbee-herdsman*'
> + npm start
> 
> > zigbee2mqtt@1.18.2 start zigbee2mqtt_cc2538/git
> > node index.js
> 
> Zigbee2MQTT:debug 20210404-153807: Can't load state from file zigbee2mqtt_cc2538/git/data/state.json (doesn't exist)
> Zigbee2MQTT:info  20210404-153807: Logging to console and directory: 'data/log' filename: Z2M_CC2538_2021-04-04.15-38-06.log
> Zigbee2MQTT:info  20210404-153808: Starting Zigbee2MQTT version 1.18.2 (commit #abd8a092)
> Zigbee2MQTT:info  20210404-153808: Starting zigbee-herdsman (0.13.88)
> Zigbee2MQTT:debug 20210404-153808: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"zigbee2mqtt_cc2538/git/data/coordinator_backup.json","databaseBackupPath":"zigbee2mqtt_cc2538/git/data/database.db.backup","databasePath":"zigbee2mqtt_cc2538/git/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6755},"serialPort":{"adapter":"zstack","baudRate":115200,"path":"/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00","rtscts":false}}'
>   zigbee-herdsman:adapter Path '/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00' is valid for 'ZStackAdapter' +0ms
>   zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6755,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00","adapter":"zstack"},"databasePath":"zigbee2mqtt_cc2538/git/data/database.db","databaseBackupPath":"zigbee2mqtt_cc2538/git/data/database.db.backup","backupPath":"zigbee2mqtt_cc2538/git/data/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}' +0ms
>   zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/serial/by-id/usb-Texas_Instruments_CC2538_USB_CDC-if00 and {"baudRate":115200,"rtscts":false,"autoOpen":false} +0ms
>   zigbee-herdsman:adapter:zStack:znp:log Serialport opened +9ms
>   zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload +464ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239] +0ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1} +0ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32] +1s
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,1,121,7,28] +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,1,121,7,28] +1ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 1 - [121,7] - 28 +1ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - ping - {"capabilities":1913} +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +4ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - version - {} +15ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,2,35] +12ms
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,97,2,2,2,2,7,2,50,62,52,1,2,255,255,255,255,81] +4ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,97,2,2,2,2,7,2,50,62,52,1,2,255,255,255,255,81] +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 1 - 2 - [2,2,2,7,2,50,62,52,1,2,255,255,255,255] - 81 +0ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - version - {"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20201010} +7ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
>   zigbee-herdsman:adapter:zStack:adapter Adapter concurrent: 2 +0ms
>   zigbee-herdsman:adapter:zStack:adapter Detected znp version 'zStack30x' ({"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20201010}) +0ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}} +8ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74] +9ms
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,8,2,0,105] +19ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,8,2,0,105] +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 8 - [2,0] - 105 +0ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}} +21ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +2ms
>   zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is invalid, got '{"type":"Buffer","data":[]}', expected '{"type":"Buffer","data":[85]}' +0ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}} +21ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74] +20ms
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,8,2,0,105] +18ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,8,2,0,105] +1ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 8 - [2,0] - 105 +0ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}} +19ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
>   zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is invalid, got '{"type":"Buffer","data":[]}', expected '{"type":"Buffer","data":[85]}' +19ms
>   zigbee-herdsman:adapter:zStack:startZnp Initialising coordinator +2ms
>   zigbee-herdsman:adapter:zStack:znp:AREQ --> SYS - resetReq - {"type":1} +0ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,1,65,0,1,65] +20ms
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,65,128,0,2,2,2,7,2,192] +2s
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,6,65,128,0,2,2,2,7,2,192] +1ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 2 - 1 - 128 - [0,2,2,2,7,2] - 192 +0ms
>   zigbee-herdsman:adapter:zStack:znp:AREQ <-- SYS - resetInd - {"reason":0,"transportrev":2,"productid":2,"majorrel":2,"minorrel":7,"hwrev":2} +2s
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +2ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":3,"len":1,"offset":0,"value":{"type":"Buffer","data":[2]}} +2s
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,3,0,0,1,2,45] +2s
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105] +10ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105] +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105 +1ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0} +2s
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +0ms
>   zigbee-herdsman:adapter:zStack:znp:AREQ --> SYS - resetReq - {"type":1} +12ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,1,65,0,1,65] +7ms
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,65,128,0,2,2,2,7,2,192] +1s
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,6,65,128,0,2,2,2,7,2,192] +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 2 - 1 - 128 - [0,2,2,2,7,2] - 192 +1ms
>   zigbee-herdsman:adapter:zStack:znp:AREQ <-- SYS - resetInd - {"reason":0,"transportrev":2,"productid":2,"majorrel":2,"minorrel":7,"hwrev":2} +1s
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +0ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":135,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}} +1s
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,135,0,0,1,0,171] +1s
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105] +10ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105] +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105 +0ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0} +1s
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":99,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}} +10ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,99,0,0,1,0,79] +11ms
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105] +11ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105] +0ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105 +1ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0} +12ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +0ms
>   zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":143,"len":1,"offset":0,"value":{"type":"Buffer","data":[1]}} +13ms
>   zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,143,0,0,1,1,162] +12ms
>   zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,10,99] +8ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,10,99] +1ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [10] - 99 +0ms
>   zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":10} +9ms
>   zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
> Zigbee2MQTT:error 20210404-153813: Error while starting zigbee-herdsman
> Zigbee2MQTT:error 20210404-153813: Failed to start zigbee
> Zigbee2MQTT:error 20210404-153813: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
> Zigbee2MQTT:error 20210404-153813: Exiting...
> Zigbee2MQTT:error 20210404-153813: Error: SREQ '--> SYS - osalNvWrite - {"id":143,"len":1,"offset":0,"value":{"type":"Buffer","data":[1]}}' failed with status '(0x0a: NV_OPER_FAILED)' (expected '(0x00: SUCCESS)')
>     at Znp.<anonymous> (zigbee2mqtt_cc2538/git/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
>     at Generator.next (<anonymous>)
>     at fulfilled (zigbee2mqtt_cc2538/git/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! zigbee2mqtt@1.18.2 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the zigbee2mqtt@1.18.2 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
>
