### ISSUE TITLE
Lonsonho TS0043 не подключается к CC2538 CC2592

### ISSUE THREAD

**Issue by sergey81-81** [jethome-ru/zigbee-firmware#7]
В наличии 3 таких устройства. Два ранее приобретённых подключил без проблем. Приобрёл ещё один, который через CC2538 не подключается. Через СС2531 подключается с первого раза.

**Comment by Hacker-CB** [comment]
Вам не сюда, а саппорт софта, который вы юзаете. (Z2m,zha,...).
Прошивка стика не играет роли в работе конкретного устройства.

**Comment by sergey81-81** [comment]
Почему замена стика CC2538 на стик СС2531 решает проблему?

**Comment by sergey81-81** [comment]
Ранее были такие же проблемы с другими устройствами. После обновления прошивки CC2538 до версии 20201010 все устройства подключились без проблем кроме этого.

**Comment by Hacker-CB** [comment]
Сложно сказать.
Стик работает по протоколу ZStack, для которого нет разницы, какое устройство «на том конце»
В любом случае, начните с создания тикета с описанием логов, версий софта и тд в репозитории высокоуровнего софта, который вы используете (z2m,zha,...)
